### ISSUE TITLE
Add 'prompt' support

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_browser#290]
as per: https://forum.safedev.org/t/safe-browser-prompt-support/1198

**Comment by hunterlester** [comment]
For implementation reference: https://github.com/beakerbrowser/beaker/pull/421/files

**Comment by joshuef** [comment]
Hmmm. Looking up the reasons why electron doesn't offer it...

https://github.com/electron/electron/issues/472

It makes sense. I certainly wouldn't implement it in a blocking fashion. And if we're not doing that... would we at all?

To me this seems like something that should be handled by the app themselves in this day and age...

Thoughts @hunterlester  @bochaco ?

**Comment by hunterlester** [comment]
If we do decide to impl in browser, this is a not bad solution: https://github.com/konsumer/electron-prompt/blob/master/main.js

Otherwise, yes web developers could simply, but perhaps tediously, set their own `window.prompt` to a function which displays a hidden `input` div, styled to look like a `prompt` modal.

**Comment by joshuef** [comment]
Problem with that is that a prompt is that it's supposed to block the rest of the window until it's resolved.

Opening a new BrowserWindow doesn't provide this behaviour. And if we're not meeting the standard browser spec, I wouldn't implement it.

**Comment by joshuef** [comment]
Closing as this is a missing electron feature. We can reopen if/when electron provide this.
