### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by nadiaburborough** [maidsafe/safe_browser#354]
1. Create a Tag for current master branch e.g. `beaker-deprecation`
2. Pull the peruse branch to master and delete the peruse branch
3. Set up the release binaries as SAFE Browser v0.11
4. There are drafts releases which are not needed anymore and that has to be deleted.
5. Update the browser links on the websites for downloading

**Comment by S-Coyle** [comment]
Discussions on step 3:
@joshuef discussed with @krishnaIndia that we should stay on the Peruse release v numbers rather than SB.
TBC - will discuss on Slack with others when online

**Comment by joshuef** [comment]
Ah yeh, just to fire in with more thoughts from last week:

The ideal may be aiming for v1, as it _is_ a huge codebase change.

And with that in mind, we'd prepare a release that has things such as 'experimental API warnings' etc, so we can better mark unreliable or soon to be deprecated features.

**Comment by S-Coyle** [comment]
Done, with a couple of additions/exceptions/points:

- Made a backup of the beaker browser master branch named `beaker_deprecation`

- Deleted master branch, then created a new master from peruse branch. Did not delete peruse branch yet - there are PRs pointing to it so will allow those to be switched over 1st. Separate issue created to delete it at a future date.

- Decided to leave name of current latest release as is - `Peruse 0.7.0` - rather than push a new tag and update the v number. I.e. all that has changed on the release page is that the draft releases have been removed, still the same Peruse 0.7.0 zips for users to download.

- Once we make some more adjustments to safe browser (peruse), such as add the icon, we intend to update safe browser v to v1.0.0

- Website link updates all handled by separate issues
