### ISSUE TITLE
Packaged browser `--debug` mode not loading browser devtools

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_browser#414]
When passing the `debug` argument on load, a packaged version of the browser should be opening devtools for both the background process window and the browser UI window.

Neither are currently loading.

**Comment by shriram2301** [comment]
@joshuef  I have been able to get the devtools working in #419 for app devtools. I have been able to get the background one also partially. Do we need both to show in debug mode? Because for the BG it might require setting the show: true and other properties also a bit of tinkering. Basically using show() and hide() based on the mode/packing .

**Comment by joshuef** [comment]
@shriram2301 we need a devtools window for both the `app` and the `bg process`. 

I'd wager you're not seeing the `bg` one, as the window is set to be invisible, which I think means that devtools dont open (on linux), i'm not sure about windows...

If that's the case, we should decide if we want both windows on all platforms... should we show the bg window (in some small capacity), to get the devtools to show up for this?

**Comment by shriram2301** [comment]
@joshuef  `bg` we could make it visible. but if by mistake someone closes the window. wouldn't it terminate the process itself and crash the whole app? if we make `bg` visible we need to find a way to tackle this.

**Comment by S-Coyle** [comment]
Issue should be closed - confirming correct board behaviour
