### ISSUE TITLE
Research / POC of external to browser auth and how IPC may function to DOM.

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_browser#459]

**Comment by hunterlester** [comment]
Had some [thoughts](https://github.com/hunterlester/safe_cli/blob/master/DESIGN.md) around this earlier this year.
It's not a high priority at this time but SCL team has discussed building and exposing a native IPC strategy.
My thoughts were focused on TCP solely because of the profuse documentation and examples, knowing that it's not as performant as other IPC strategies, HOWEVER, having a TCP implementation may be useful, say, for a single Authenticator instance providing service to multiple remote client applications.

My first choice was to model Chromium's IPC implementations, [named Mutexes](https://github.com/electron/electron/blob/master/chromium_src/chrome/browser/process_singleton_win.cc#L270) for Windows and [Unix domain sockets](https://github.com/electron/electron/blob/master/chromium_src/chrome/browser/process_singleton_posix.cc#L5) for *nix.

**Comment by joshuef** [comment]
closing as we've POC in place. we can continue IPC discussion in an issue dedicated to that.
