### ISSUE TITLE
Getting error while creating WebID, but it is actually created and listed after page refresh

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe_browser#470]
When I try to create a WebID using latest webid manager, it is showing an error saying `Error creating webid on the network` and If I switch to list tab from create tab it lists the id which was just throwing the error. 

Note: I used my old account which was created before rc2, for creating webid. Tested on Windows and Ubuntu cc: @bochaco 

![image](https://user-images.githubusercontent.com/27578024/49893655-f893de80-fe71-11e8-9a1f-54b777533f6c.png)

![image](https://user-images.githubusercontent.com/27578024/49893672-02b5dd00-fe72-11e8-8570-d54ae4133fbf.png)

**Comment by bochaco** [comment]
Thanks a lot @safesurfer , I'm investigating why some of the entries in the _publicNames container of your account throw an unexpected error when trying to decrypt them.

**Comment by bochaco** [comment]
After further research I'm quite sure this has to do with the revocation of an app. After revoking one of the apps that has encrpyted and stored entries in the `_publicNames` container, and there is another app which is trying to decrypt them it cannot. I presume it's because they were re-encrypted with new keys during the revocation process. 

I thought that re-authorisaing any of apps they should be able to decrypt the entries again, but from my quick test it's still not able to decrypt the enctries. But for sure I got an account to be in the same state as yours Srini after I revoke the WHM. I'll try to reproduce it tomorrow again and report the steps more clearly and hopefully be able to report it in a bug, don't know yet but if it is related to revocation it's likely to be in the safe_client_libs revocation algorithm, we'll see...

**Comment by bochaco** [comment]
Upgrading safe-app-nodejs to incude the fixe from this PR: https://github.com/maidsafe/safe_app_nodejs/pull/328 will solve this issue, see the description in that PR for the details of the issue, which are confirmed to happen after an app is revoked.

**Comment by safesurfer** [comment]
QA verified
