### ISSUE TITLE
Enable auto updates

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_browser#701]
Todo: 

- [x] Update release repo in `package.json`: https://github.com/maidsafe/safe_browser/pull/702/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R183
- [x] Check out adding a menu option for this! https://github.com/electron-userland/electron-builder/blob/docs/encapsulated%20manual%20update%20via%20menu.js
- [x] Ensure auto update is not triggered in dev mode

**Comment by hunterlester** [comment]
On Ubuntu Linux, I'm able to deploy packages from my local system to my `safe_browser` fork.
When I download the `.zip` and extract the resources, I'm able to execute the browser in my terminal via `./safe-browser` however, I'm not able to execute by double-clicking the GUI `safe-browser` files.
Secondly, the package is not bundled with a `crust.config`, which I have to add in order to connect to Alpha 2.

**Comment by hunterlester** [comment]
@joshuef @S-Coyle Tested on Windows as well. I'm able to GUI execute the installer to install SAFE Browser on the system. Same as Linux, can execute but it just doesn't have a `crust.config` bundled so cannot connect to Alpha 2.
Good news then for both platforms.
Need to understand why `electron-builder` is not creating a proper GUI executable for Linux and for both why no `crust.config` bundled.

**Comment by hunterlester** [comment]
Missing `crust.config` is a simply resolved by adding it to `extraFiles`. Looking up config such that file is named by platform.

**Comment by hunterlester** [comment]
Blocked on Linux by #809
