### ISSUE TITLE
Links open up in Chrome by default, not in the SAFE Browser

### ISSUE THREAD

**Issue by AxlMaid** [maidsafe/safe_browser#76]
Operation System: MacOS X
Beaker Version: ?

When I click links in the SAFE Browser (e.g. the "Here are few example applications to start with" link on the home page), the links open up in Google Chrome instead of opening in the SAFE Browser.

Please let me know if you need more information in order to debug.

Thank you,

Alexandre
<img width="668" alt="screen shot 2017-07-17 at 00 15 54" src="https://user-images.githubusercontent.com/30219645/28251775-1c28cbb2-6a85-11e7-9752-38fd5fc57f14.png">

**Comment by krishnaIndia** [comment]
We do not open `http` links in the safe browser unless the user toggles the `clearnet` access. If clearnet access is toggled then `safe:` wont work. Either clearnet(http or https) or `safe` will work on the browser at a time. We do not allow clearnet and safenet to be accessed at the same time.

Since, we don't have everything yet on safenet, we open the non `safe` links on external browser time being and even this will be blocked eventually and making it even stricter.

**Comment by AxlMaid** [comment]
To improve the user experience I would recommend to remain on the SAFE Browser once the use has started surfing with this browser. The SAFE browser could show some kind of differentiator (e.g. the picture of a padlock) when user is actually surfing on a secure website (i.e. on the MAID Safe network) or on a normal website (i.e. outside Maid).

Conversely I would recommend that the SAFE Browser is launched whenever the user clicks on a secure website (on MAID) from normal internet on e.g. Chrome.

Thank you,

Axl

**Comment by joshuef** [comment]
Closing as this is desired behaviour as things stand.

@AxlMaid the option exists to toggle 'safe mode' (via the `File` menu).

> Conversely I would recommend that the SAFE Browser is launched whenever the user clicks on a secure website (on MAID) from normal internet on e.g. Chrome.

Safe browser should be registering itself on the systems to handle `safe:` uris in the latest versions.

@AxlMaid if not, please let us know and we can make a specific issue for that. Thanks! 👍
