### ISSUE TITLE
Ensure there is some error indicative of auth issues

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_browser#979]

**Comment by S-Coyle** [comment]
Tests ran:
- Tested attempting to register a new site on the browser without the authenticator running and I see the `Network Connection Failed. There was a timeout. Try restarting the browser` pop up.

- Tried running the authenticator and attempting to register a site again. When the `Allow authorisation` prompt in the authenticator appeared I entered `n` - the browser displayed a 404 rather than an authentication error which I was expecting. I don't believe this is an issue worth raising though as for now the authenticator & clients such as the browser run on the same machine so it seems unlikely that a user would reject their own authentication prompt & then not know why the browser action did not succeed.
